package com.email.TriggerEmail.service;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class TriggerEmailServiceImpl implements TriggerEmailService {
	static final Logger logger = LogManager.getLogger(TriggerEmailServiceImpl.class.getName());

	@Value("${mail.smtp.from}")
	private String FROM_MAIL_ID;

	@Value("${mail.smtp.host}")
	private String SMTP_SERVER_HOST;
	@Value("${mail.smtp.port}")
	private String SMTP_SERVER_PORT;

	public boolean sendMail(String mailId) throws ParseException {
		try {
			MimeMessage msg = new MimeMessage(getSession());
			msg.setFrom(new InternetAddress(FROM_MAIL_ID));
			msg.setSubject("Confirmation of submission of resignation to your Reporting manager");

			Object object = "<html>\n" + "<body>\n" + "\n" + "<p>Dear Harshitacharya.kadekaru,</p>\r\n"
					+ "<p><br />This is to confirm that your resignation submitted by you on 17-09-2018, has been forwarded to your reporting manger as below.</p>\r\n"
					+ "<p><br />Supervisor ID : 29766</p>\r\n" + "<p>Supervisor Name : T V Mahesh</p>\r\n"
					+ "<p><br />Regards,<br />Associate Services</p>"
					+ "<p><br />Note: This message is generated by ITC Infotech ERP system OnePOINT. This message is for the exclusive use of ITC Infotech employees only.</p>\r\n"
					+ "</body>\n" + "</html>";

			msg.setContent(object, "text/html");

			DateFormat sourceFormat = new SimpleDateFormat("dd/MM/yyyy");
			String dateAsString = "17/09/2018";
			Date date = sourceFormat.parse(dateAsString);
			msg.setSentDate(date);
			msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(mailId));
			logger.info("Message is ready");
			Transport.send(msg);
			logger.info("EMail Sent Successfully!!");
		} catch (RuntimeException | MessagingException re) {
			logger.error(re.getMessage());
			return false;
		}
		return true;
	}

	private Session getSession() {
		Properties props = new Properties();
		props.put("mail.smtp.from", FROM_MAIL_ID);
		props.put("mail.smtp.host", SMTP_SERVER_HOST);
		props.put("mail.smtp.port", SMTP_SERVER_PORT);
		Session session = Session.getInstance(props, new javax.mail.Authenticator() {
		});
		return session;
	}

}
