spring:
 profiles:
    active: local
---
spring:
  profiles: local
  dataSource:
    continueOnError: true
    driver-class-name : com.mysql.jdbc.Driver
    URL: jdbc:mysql://localhost:3306/mydb?useSSL=false&characterEncoding=UTF-8
    userName: root
    password: admin@123
    #connectionProperties: useUnicode=true;characterEncoding=UTF-8
    
  JPA:
    properties:
     HIBERNATE:
        dialect: org.hibernate.dialect.MySQL5Dialect
        use_nationalized_character_data: true
        DDL-auto: create

server:
  port: 8080
  session:
    context-path: /customer
---  
spring:
  session.store-type : none  
  application:
    name: customer

mail.smtp.host: 10.6.12.154
mail.smtp.port : 25
mail.smtp.from : onepoint.HR@itcinfotech.com
